export const categories = [
  'Analytics',
  'CMS',
  'Database',
  'Date',
  'Deployment',
  'Devtools',
  'Extensions',
  'Ecommerce',
  'Fonts',
  'Images',
  'Libraries',
  'Monitoring',
  'Payment',
  'Performance',
  'Request',
  'SEO',
  'Security',
  'UI',
]

export const categoriesWithIcons = [
  { name: 'Analytics', icon: 'bar-chart' },
  { name: 'CMS', icon: 'file-text' },
  { name: 'Database', icon: 'database' },
  { name: 'Date', icon: 'calendar' },
  { name: 'Deployment', icon: 'upload-cloud' },
  { name: 'Devtools', icon: 'wrench' },
  { name: 'Extensions', icon: 'puzzle' },
  { name: 'Ecommerce', icon: 'shopping-cart' },
  { name: 'Fonts', icon: 'type' },
  { name: 'Images', icon: 'image' },
  { name: 'Libraries', icon: 'library' },
  { name: 'Monitoring', icon: 'activity' },
  { name: 'Payment', icon: 'credit-card' },
  { name: 'Performance', icon: 'gauge' },
  { name: 'Request', icon: 'send' },
  { name: 'SEO', icon: 'search' },
  { name: 'Security', icon: 'shield' },
  { name: 'UI', icon: 'layout' },
]